GUI:
  Top: WHITE_STAINED_GLASS_PANE
  Bottom: PURPLE_STAINED_GLASS_PANE

Fangster:
  1:
    Name: "FISK"
    Item-Type: RAW_FISH
    Enchanted: true
    Chance: 50
    Messages:
    - "du fangede en FISK"
    Commands:
    - ""
  2:
    Name: "&DKAGE"
    Item-Type: CAKE
    Enchanted: false
    Chance: 50
    Messages:
      - "du fangede en kage og 10 kr"
    Commands:
      - "eco give %player% 10"